"""Convert the `.ovf` files generated by mumax into a single numpy array of
shape (n_frames, nz, ny, nx, 3), where

    - n_frames is the number of output files generated by mumax
    - (nz, ny, nx) are the number of simulation cells in the z, y, and x directions, respectively
    - the last dimension of length 3 contains the magnetization vector for each cell, (mx, my, mz)

The mx3tools package can be found at `https://github.com/peytondmurray/mx3tools`
"""
import numpy as np
from mx3tools import ovftools


def to_npy():
    data = ovftools.group_unpack('./jdh.out')
    np.save('data.npy', data)


if __name__ == "__main__":
    to_npy()
